project:
  type: website
  resources:
    - README.md
    - 404.qmd
execute:
  freeze: auto

# tell quarto to read the sidebar file
metadata-files:
  - _sidebar.yml
# tell quartodoc to generate the sidebar file
quartodoc:
  sidebar: "_sidebar.yml"
  # other options ...

website:
  title: "QMD的杂物间"
  description: "琐事随笔"
  site-url: https://qmdthings.top
  # you must change this appropriately for RSS feeds to work properly

  reader-mode: true

  # Search
  search:
    location: sidebar

  # body-header: |
  #   ---
  #
  # body-footer: |
  #   ---
  #
  # margin-header: ""
  #
  # margin-footer: ""

  # Page
  page-navigation: true
  # back-to-top-navigation: true
  page-footer:
    center: "毎日マリーゴールドを1つ"

  # NavBar
  navbar:
    title: "Navi"
    background: "#4E9AB0"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - sidebar:blogs
      - sidebar:fun
    right:
      - icon: rss
        href: index.xml

  # SideBar
  sidebar:
    - id: blogs
      title: "Blogs"
      contents: posts
      tools:
        - icon: github
          href: https://github.com/

    - id: fun
      title: "Fun"

  # announcement:
  #   content: "欢迎!"
  #   position: below-navbar

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
